---
output:
  github_document:
    df_print: paged
---

## R packages by Pepijn

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

This site is still under construction. Meanwhile check out my R packages.

```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(httr2)
library(jsonlite)
library(dplyr)

packages <-
  "https://raw.githubusercontent.com/pepijn-devries/pepijn-devries.r-universe.dev/main/packages.json" |>
    request() |> req_perform() |> resp_body_string() |> fromJSON() |>
  mutate(
    package_raw = .data$package,
    package = paste0("<a href=\"https://pepijn-devries.github.io/", .data$package, "/\">",
                     .data$package, "</a>"),
    tags = .data$tags |> lapply(sort) |> lapply(paste0, collapse = ", ") |> unlist()
  ) |>
  dplyr::arrange(.data$package, .data$tags)

packages |> select("package", "tags") |> as.data.frame() |> knitr::kable("html", escape = FALSE)
```


```{r, echo = FALSE, warning=FALSE, message=FALSE}
template  <- readLines("_pkgdown_template.yml")
menu      <- grepl("[menu]", template, fixed = TRUE) |> which()
spaces    <- gregexpr(" ", template[[menu]])[[1]] |> length()
spaces    <- strrep(" ", spaces)
menu_text <- cbind(
    sprintf("%s- text: %s (%s)", spaces, packages$package_raw, packages$tags),
    sprintf("%s  href: %s/", spaces, packages$package_raw)
  ) |> t() |> c()
template <-
  c(
    template[seq_len(menu - 1)],
    menu_text,
    template[(menu + 1):length(template)]
  )
writeLines(
  template,
  "_pkgdown.yml"
)
```
